Repository NNPDF/eko, pull requests merged in 2022-07, with the labels that each got.

#132 Speeding up N3LO matching
  src/eko/evolution_operator/__init__.py
  src/eko/matching_conditions/as3/__init__.py
  src/eko/matching_conditions/as3/aHg.py
  src/eko/matching_conditions/as3/aHgstfac.py
  src/eko/matching_conditions/as3/aHq.py
  src/eko/matching_conditions/as3/agg.py
  src/eko/matching_conditions/as3/aggTF2.py
  src/eko/matching_conditions/as3/agq.py
  src/eko/matching_conditions/as3/aqg.py
  src/eko/matching_conditions/as3/aqqNS.py
  src/eko/matching_conditions/as3/aqqPS.py
  src/eko/matching_conditions/operator_matrix_element.py
  tests/eko/test_ad_as4.py
  tests/eko/test_ev_operator.py
  tests/eko/test_matching_n3lo.py
  tests/eko/test_matching_nlo.py
  tests/eko/test_matching_nnlo.py
  tests/eko/test_ome.py
Labels: refactor

#125 Fix scale variations scheme B
  benchmarks/lha_paper_bench.py
  doc/source/theory/pQCD.rst
  src/eko/anomalous_dimensions/as4/ggg.py
  src/eko/anomalous_dimensions/as4/gps.py
  src/eko/anomalous_dimensions/as4/gqg.py
  src/eko/evolution_operator/__init__.py
  src/eko/evolution_operator/grid.py
  src/eko/harmonics/f_functions/f11.py
  src/eko/harmonics/f_functions/f13.py
  src/eko/harmonics/f_functions/f14_f12.py
  src/eko/harmonics/f_functions/f16.py
  src/eko/harmonics/f_functions/f17.py
  src/eko/harmonics/f_functions/f18.py
  src/eko/harmonics/f_functions/f19.py
  src/eko/harmonics/f_functions/f20.py
  src/eko/harmonics/f_functions/f21.py
  src/eko/harmonics/f_functions/f9.py
  src/eko/matching_conditions/as3/aHg.py
  src/eko/matching_conditions/as3/aHgstfac.py
  src/eko/matching_conditions/as3/agg.py
  src/eko/matching_conditions/operator_matrix_element.py
  src/eko/scale_variations/__init__.py
  src/eko/scale_variations/expanded.py
  src/ekobox/utils.py
  tests/eko/test_couplings.py
  tests/eko/test_ev_op_grid.py
  tests/eko/test_ev_operator.py
  tests/eko/test_msbar_masses.py
  tests/eko/test_sv_expanded.py
Labels: bug, enhancement, physics

#137 N3LO singlet ad
  .pre-commit-config.yaml
  doc/source/refs.bib
  doc/source/shared/abbreviations.rst
  doc/source/theory/N3LO_ad.rst
  extras/n3lo_ad.tar.gz
  src/eko/anomalous_dimensions/as4/ggg.py
  src/eko/anomalous_dimensions/as4/ggq.py
  src/eko/anomalous_dimensions/as4/gps.py
  src/eko/anomalous_dimensions/as4/gqg.py
  src/eko/harmonics/log_functions.py
  src/eko/interpolation.py
  src/eko/mellin.py
  tests/eko/test_ad_as4.py
  tests/eko/test_harmonics_log_functions.py
Labels: enhancement, physics
