Repository NNPDF/eko, pull requests merged in 2023-01, with the labels that each got.

#187 Refactor couplings tests
  tests/eko/test_couplings.py
Labels: refactor

#196 Use filesystem safe b64
  src/eko/io/struct.py
Labels: bug, output

#191 Fix scale variations expanded
  src/eko/evolution_operator/__init__.py
  src/eko/matching_conditions/operator_matrix_element.py
  src/eko/scale_variations/expanded.py
  tests/eko/evolution_operator/test_init.py
  tests/eko/scale_variations/test_expanded.py
Labels: bug, refactor

#199 Check matching
  benchmarks/eko/benchmark_msbar_evolution.py
  benchmarks/eko/benchmark_strong_coupling.py
  extras/matching/.gitignore
  extras/matching/check-matching.py
  extras/matching/style.yaml
  extras/matching/utils.py
  src/eko/couplings.py
  src/eko/msbar_masses.py
  src/eko/runner/legacy.py
  tests/eko/test_couplings.py
  tests/eko/test_msbar_masses.py
Labels: bug
