Repository NNPDF/eko, pull requests merged in 2023-04, with the labels that each got.

#238 Fix IO for LHA bot
  benchmarks/lha_paper_bench.py
  doc/source/code/IO.rst
  src/eko/io/runcards.py
  src/ekomark/benchmark/external/LHA_utils.py
  src/ekomark/navigator/navigator.py
  tests/eko/io/test_runcards.py
Labels: bug, benchmarks

#232 Time Like Splitting Functions
  benchmarks/FF_LHAPDF_bench.py
  benchmarks/eko/benchmark_evol_to_unity.py
  doc/source/index.rst
  doc/source/refs.bib
  doc/source/shared/abbreviations.rst
  doc/source/theory/TimeLike.rst
  pyproject.toml
  src/eko/evolution_operator/flavors.py
  src/eko/evolution_operator/grid.py
  src/ekomark/benchmark/external/lhapdf_utils.py
  src/ekore/anomalous_dimensions/unpolarized/space_like/as4/gnsm.py
  src/ekore/anomalous_dimensions/unpolarized/time_like/__init__.py
  src/ekore/anomalous_dimensions/unpolarized/time_like/as1.py
  src/ekore/anomalous_dimensions/unpolarized/time_like/as2.py
  src/ekore/anomalous_dimensions/unpolarized/time_like/as3.py
  tests/eko/evolution_operator/test_grid.py
  tests/eko/evolution_operator/test_init.py
  tests/ekore/anomalous_dimensions/unpolarized/space_like/test_as4.py
  tests/ekore/anomalous_dimensions/unpolarized/time_like/test_as1.py
  tests/ekore/anomalous_dimensions/unpolarized/time_like/test_as2.py
  tests/ekore/anomalous_dimensions/unpolarized/time_like/test_as3.py
  tests/ekore/anomalous_dimensions/unpolarized/time_like/test_init.py
  tests/ekore/harmonics/test_g_functions.py
  tests/ekore/harmonics/test_polygamma.py
  tests/ekore/operator_matrix_elements/unpolarized/space_like/test_n3lo.py
  tests/ekore/operator_matrix_elements/unpolarized/space_like/test_nlo.py
  tests/ekore/operator_matrix_elements/unpolarized/space_like/test_nnlo.py
Labels: enhancement, physics

#243 Fix pydocstyle
  .pre-commit-config.yaml
  src/eko/gamma.py
  src/eko/interpolation.py
  src/eko/kernels/__init__.py
  src/eko/kernels/utils.py
  src/eko/mellin.py
  src/eko/member.py
  src/ekobox/genpdf/cli.py
  src/ekobox/genpdf/flavors.py
  src/ekobox/mock.py
  src/ekomark/__init__.py
  src/ekomark/benchmark/__init__.py
  src/ekomark/benchmark/external/__init__.py
  src/ekomark/data/__init__.py
  src/ekomark/navigator/__init__.py
  src/ekomark/navigator/glob.py
  src/ekore/__init__.py
  src/ekore/anomalous_dimensions/__init__.py
  src/ekore/anomalous_dimensions/polarized/__init__.py
  src/ekore/anomalous_dimensions/unpolarized/__init__.py
  src/ekore/anomalous_dimensions/unpolarized/space_like/as4/__init__.py
  src/ekore/anomalous_dimensions/unpolarized/space_like/as4/ggg.py
  src/ekore/anomalous_dimensions/unpolarized/space_like/as4/ggq.py
  src/ekore/anomalous_dimensions/unpolarized/space_like/as4/gnsm.py
  src/ekore/anomalous_dimensions/unpolarized/space_like/as4/gnsp.py
  src/ekore/anomalous_dimensions/unpolarized/space_like/as4/gnsv.py
  src/ekore/anomalous_dimensions/unpolarized/space_like/as4/gps.py
  src/ekore/anomalous_dimensions/unpolarized/space_like/as4/gqg.py
  src/ekore/harmonics/g_functions.py
  src/ekore/harmonics/polygamma.py
  src/ekore/harmonics/w1.py
  src/ekore/harmonics/w2.py
  src/ekore/harmonics/w3.py
  src/ekore/harmonics/w4.py
  src/ekore/operator_matrix_elements/__init__.py
  src/ekore/operator_matrix_elements/polarized/__init__.py
  src/ekore/operator_matrix_elements/polarized/space_like/__init__.py
  src/ekore/operator_matrix_elements/unpolarized/__init__.py
  src/ekore/operator_matrix_elements/unpolarized/space_like/__init__.py
  src/ekore/operator_matrix_elements/unpolarized/space_like/as1.py
  src/ekore/operator_matrix_elements/unpolarized/space_like/as2.py
  src/ekore/operator_matrix_elements/unpolarized/space_like/as3/__init__.py
  src/ekore/operator_matrix_elements/unpolarized/space_like/as3/aHg.py
  src/ekore/operator_matrix_elements/unpolarized/space_like/as3/aHgstfac.py
  src/ekore/operator_matrix_elements/unpolarized/space_like/as3/aHq.py
  src/ekore/operator_matrix_elements/unpolarized/space_like/as3/agg.py
  src/ekore/operator_matrix_elements/unpolarized/space_like/as3/aggTF2.py
  src/ekore/operator_matrix_elements/unpolarized/space_like/as3/agq.py
  src/ekore/operator_matrix_elements/unpolarized/space_like/as3/aqg.py
  src/ekore/operator_matrix_elements/unpolarized/space_like/as3/aqqNS.py
  src/ekore/operator_matrix_elements/unpolarized/space_like/as3/aqqPS.py
  src/ekore/operator_matrix_elements/unpolarized/time_like/__init__.py
Labels: documentation

#247 Fix backward matching
  src/eko/evolution_operator/operator_matrix_element.py
  tests/eko/evolution_operator/test_matching_condition.py
  tests/eko/evolution_operator/test_ome.py
Labels: bug

#245 Time like matching conditions
  benchmarks/FF_LHAPDF_bench.py
  doc/source/refs.bib
  doc/source/theory/TimeLike.rst
  src/eko/evolution_operator/operator_matrix_element.py
  src/ekore/anomalous_dimensions/unpolarized/time_like/__init__.py
  src/ekore/anomalous_dimensions/unpolarized/time_like/as1.py
  src/ekore/anomalous_dimensions/unpolarized/time_like/as2.py
  src/ekore/anomalous_dimensions/unpolarized/time_like/as3.py
  src/ekore/operator_matrix_elements/unpolarized/time_like/__init__.py
  src/ekore/operator_matrix_elements/unpolarized/time_like/as1.py
  tests/eko/evolution_operator/test_ome.py
  tests/ekore/operator_matrix_elements/unpolarized/time_like/test_as1.py
  tests/ekore/operator_matrix_elements/unpolarized/time_like/test_init.py
Labels: enhancement, physics

#250 time-like ome fix at nnlo
  src/ekore/operator_matrix_elements/unpolarized/time_like/__init__.py
  tests/eko/evolution_operator/test_ome.py
Labels: bug
