Repository NNPDF/eko, pull requests merged in 2024-07, with the labels that each got.

#354 N3LO benchmark study
  extras/lh_bench_23/.gitignore
  extras/lh_bench_23/cfg.py
  extras/lh_bench_23/parse_to_latex.py
  extras/lh_bench_23/plot_bench.py
  extras/lh_bench_23/plot_bench_evol.py
  extras/lh_bench_23/plot_bench_msht.py
  extras/lh_bench_23/plot_trn_exa.py
  extras/lh_bench_23/run-n3lo.py
  extras/lh_bench_23/run-nnlo.py
  extras/lh_bench_23/run-trn_exa.py
  extras/lh_bench_23/run_fhmruvv.sh
  extras/lh_bench_23/tables/EKO.zip
  extras/lh_bench_23/tables/MSHT.zip
  extras/lh_bench_23/tables/table14-part1.csv
  extras/lh_bench_23/tables/table15-part1.csv
  extras/lh_bench_23/tables/table_FFNS-1_iterate-exact.csv
  extras/lh_bench_23/tables/table_FFNS-1_truncated.csv
  extras/lh_bench_23/tables/table_FFNS-2_iterate-exact.csv
  extras/lh_bench_23/tables/table_FFNS-2_truncated.csv
  extras/lh_bench_23/tables/table_FFNS-3_iterate-exact.csv
  extras/lh_bench_23/tables/table_FFNS-3_truncated.csv
  extras/lh_bench_23/utils.py
Labels: benchmarks

#380 Add new P_gq parametrisation
  doc/source/refs.bib
  doc/source/theory/N3LO_ad.rst
  extras/n3lo_bench/plot_msht.py
  src/ekore/anomalous_dimensions/unpolarized/space_like/as4/fhmruvv/ggq.py
  src/ekore/anomalous_dimensions/unpolarized/space_like/as4/ggq.py
  tests/ekore/anomalous_dimensions/unpolarized/space_like/test_as4.py
  tests/ekore/anomalous_dimensions/unpolarized/space_like/test_as4_fhmv.py
Labels: physics

#391 Use nf to generate alpha_s
  src/ekobox/evol_pdf.py
  src/ekobox/info_file.py
  src/ekobox/utils.py
  tests/ekobox/test_evol_pdf.py
  tests/ekobox/test_info_file.py
Labels: enhancement

#393 Allow abbrev in rust doc
  crates/doc-header.html
  crates/eko/Cargo.toml
  crates/eko/doc-header.html
  crates/eko/katex-header.html
  crates/ekore/Cargo.toml
  crates/ekore/doc-header.html
  crates/ekore/katex-header.html
  crates/katex-header.html
  crates/parse-abbrev.py
Labels: documentation, rust

#395 Pass evolution + backwards method internally via int
  src/eko/evolution_operator/__init__.py
  src/eko/evolution_operator/__init__.py.patch
  src/eko/evolution_operator/grid.py
  src/eko/evolution_operator/operator_matrix_element.py
  src/eko/kernels/__init__.py
  src/eko/kernels/non_singlet.py
  src/eko/kernels/non_singlet_qed.py
  src/eko/kernels/singlet.py
  src/eko/kernels/singlet_qed.py
  src/eko/kernels/valence_qed.py
  src/eko/scale_variations/__init__.py
  src/ekomark/data/operators.py
  tests/eko/evolution_operator/test_init.py
  tests/eko/evolution_operator/test_ome.py
  tests/eko/kernels/test_init.py
  tests/eko/kernels/test_kernels_QEDns.py
  tests/eko/kernels/test_kernels_QEDsinglet.py
  tests/eko/kernels/test_kernels_QEDvalence.py
  tests/eko/kernels/test_ns.py
  tests/eko/kernels/test_s.py
  tests/eko/scale_variations/test_diff.py
  tests/eko/scale_variations/test_expanded.py
Labels: refactor
