Repository NNPDF/eko, pull requests merged in 2024-01, with the labels that each got.

#338 Update couplings docs
  src/eko/couplings.py
Labels: documentation

#336 Pass nl as an argument in qed beta functions
  benchmarks/eko/benchmark_alphaem.py
  src/eko/beta.py
  src/eko/constants.py
  src/eko/couplings.py
  src/eko/evolution_operator/__init__.py
  src/eko/matchings.py
  src/eko/scale_variations/exponentiated.py
  tests/eko/evolution_operator/test_init.py
  tests/eko/scale_variations/test_exponentiated.py
  tests/eko/test_beta.py
Labels: enhancement, physics

#189 Introduce Rust extension
  .pre-commit-config.yaml
  crates/.gitignore
  crates/Cargo.lock
  crates/Cargo.toml
  crates/eko/Cargo.toml
  crates/eko/pyproject.toml
  crates/eko/src/lib.rs
  crates/eko/src/mellin.rs
  crates/ekore/Cargo.toml
  crates/ekore/refs.bib
  crates/ekore/src/anomalous_dimensions.rs
  crates/ekore/src/anomalous_dimensions/unpolarized.rs
  crates/ekore/src/anomalous_dimensions/unpolarized/spacelike.rs
  crates/ekore/src/anomalous_dimensions/unpolarized/spacelike/as1.rs
  crates/ekore/src/bib.rs
  crates/ekore/src/constants.rs
  crates/ekore/src/harmonics.rs
  crates/ekore/src/harmonics/cache.rs
  crates/ekore/src/harmonics/polygamma.rs
  crates/ekore/src/harmonics/w1.rs
  crates/ekore/src/lib.rs
  crates/ekore/src/util.rs
  crates/make_bib.py
  poetry.lock
  pyproject.toml.patch
  rustify.sh
  src/eko/evolution_operator/__init__.py.patch
  src/eko/evolution_operator/quad_ker.py
  tests/eko/evolution_operator/test_init.py.patch
Labels: refactor, rust
