Repository NNPDF/eko, pull requests merged in 2024-08, with the labels that each got.

#291 Add mypy
  .pre-commit-config.yaml
  src/eko/couplings.py
  src/eko/evolution_operator/__init__.py
  src/eko/evolution_operator/__init__.py.patch
  src/eko/evolution_operator/grid.py
  src/eko/evolution_operator/operator_matrix_element.py
  src/eko/io/inventory.py
  src/eko/io/legacy.py
  src/eko/io/struct.py
  src/eko/io/types.py
  src/eko/msbar_masses.py
  src/eko/quantities/couplings.py
  src/eko/runner/operators.py
  src/eko/runner/parts.py
  src/eko/scale_variations/__init__.py
  src/ekobox/apply.py
  src/ekobox/cli/inspect.py
  src/ekobox/cli/run.py
  src/ekobox/cli/runcards.py
  src/ekobox/evol_pdf.py
  src/ekobox/genpdf/__init__.py
  src/ekobox/info_file.py
  src/ekomark/plots.py
  tests/eko/evolution_operator/test_init.py
  tests/eko/quantities/test_couplings.py
  tests/eko/test_couplings.py
Labels: benchmarks

#292 Change `manipulate` to act on Operator
  src/eko/io/bases.py
  src/eko/io/manipulate.py
  src/eko/io/metadata.py
  src/eko/io/struct.py
  src/ekobox/apply.py
  src/ekomark/benchmark/runner.py
  src/ekomark/plots.py
  tests/eko/io/test_bases.py
  tests/eko/io/test_manipulate.py
  tests/eko/io/test_metadata.py
  tests/eko/io/test_runcards.py
  tests/eko/runner/__init__.py
  tests/eko/runner/conftest.py
  tests/ekobox/test_apply.py
Labels: enhancement, output

#295 Next runcards update
  benchmarks/eko/benchmark_alphaem.py
  benchmarks/eko/benchmark_evol_to_unity.py
  benchmarks/eko/benchmark_inverse_matching.py
  benchmarks/eko/benchmark_msbar_evolution.py
  benchmarks/eko/benchmark_strong_coupling.py
  benchmarks/ekobox/benchmark_evol_pdf.py
  benchmarks/lha_paper_bench.py
  doc/source/overview/tutorials/alpha_s.ipynb
  doc/source/overview/tutorials/dglap.ipynb
  doc/source/overview/tutorials/output.ipynb
  doc/source/overview/tutorials/pdf.ipynb
  extras/n3lo_bench/splitting_function_utils.py
  src/eko/couplings.py
  src/eko/evolution_operator/grid.py
  src/eko/evolution_operator/matching_condition.py
  src/eko/evolution_operator/operator_matrix_element.py
  src/eko/evolution_operator/physical.py
  src/eko/io/legacy.py
  src/eko/io/runcards.py
  src/eko/io/struct.py
  src/eko/msbar_masses.py
  src/eko/quantities/couplings.py
  src/eko/quantities/heavy_quarks.py
  src/eko/runner/commons.py
  src/eko/runner/legacy.py
  src/eko/runner/managed.py
  src/eko/runner/parts.py
  src/ekobox/cards.py
  src/ekobox/cli/runcards.py
  src/ekobox/info_file.py
  src/ekobox/utils.py
  src/ekomark/data/__init__.py
  tests/eko/evolution_operator/test_grid.py
  tests/eko/evolution_operator/test_matching_condition.py
  tests/eko/evolution_operator/test_ome.py
  tests/eko/evolution_operator/test_physical.py
  tests/eko/io/test_runcards.py
  tests/eko/kernels/test_kernels_QEDns.py
  tests/eko/quantities/test_couplings.py
  tests/eko/runner/test_legacy.py
  tests/eko/scale_variations/test_diff.py
  tests/eko/scale_variations/test_expanded.py
  tests/eko/test_couplings.py
  tests/eko/test_msbar_masses.py
  tests/eko/test_quantities.py
  tests/ekobox/test_cards.py
  tests/ekobox/test_evol_pdf.py
  tests/ekobox/test_info_file.py
  tests/ekobox/test_utils.py
  tests/ekomark/data/__init__.py
  tests/ekomark/data/test_init.py
Labels: enhancement, output

#296 Improve runner API
  extras/matching/check-matching.py
  src/eko/io/access.py
  src/eko/io/legacy.py
  src/eko/io/metadata.py
  src/eko/io/struct.py
  src/eko/runner/__init__.py
  src/eko/runner/legacy.py
  src/eko/runner/managed.py
  src/eko/runner/operators.py
  src/eko/runner/parts.py
  src/eko/runner/recipes.py
  src/ekobox/utils.py
  tests/eko/io/test_struct.py
  tests/eko/runner/conftest.py
  tests/eko/runner/test_operators.py
  tests/eko/runner/test_parts.py
  tests/eko/runner/test_recipes.py
Labels: enhancement, output

#400 EKO Rust reader v2
  .github/workflows/unittests-rust.yml
  .pre-commit-config.yaml
  Cargo.lock
  Cargo.toml
  crates/dekoder/Cargo.toml
  crates/dekoder/doc-header.html
  crates/dekoder/src/eko.rs
  crates/dekoder/src/inventory.rs
  crates/dekoder/src/lib.rs
  crates/dekoder/tests/data/.gitignore
  crates/dekoder/tests/data/download.sh
  crates/dekoder/tests/test_load.rs
  crates/doc-header.html
  crates/ekore/refs.bib
  crates/ekore/src/bib.rs
  pyproject.toml
Labels: rust, output
